# Learn more about configuring your extension and Shopify extension types:
# https://shopify.dev/docs/apps/tools/cli/configuration

api_version = "2024-04"


[[extensions]]
type = "ui_extension"
name = "Share Spike Block"
handle = "share-spike-block"

  [extensions.build]
  dev_cmd = "npm run dev"
  build_cmd = "npm run build"
  external = ["react-reconciler"]

  [extensions.capabilities]
  network_access = true

  [[extensions.targeting]]
  target = "purchase.thank-you.block.render"
  module = "./src/index.jsx"
