# fly.toml app configuration file generated for sharespike on 2025-04-06T14:24:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sharespike'
primary_region = 'bom'

[env ]
PORT = '3000'
SHOPIFY_APP_URL = 'https://sharespike.fly.dev/'
SHOPIFY_API_KEY = 'd3974da956e097f931aa11d357cadfba'
SCOPES = 'write_products'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
