# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d3974da956e097f931aa11d357cadfba"
name = "ShareSpike"
handle = "sharespike"
application_url = "https://coat-renew-excellent-identify.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://coat-renew-excellent-identify.trycloudflare.com/auth/callback",
  "https://coat-renew-excellent-identify.trycloudflare.com/auth/shopify/callback",
  "https://coat-renew-excellent-identify.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
